resources:
  # Web Application Tier
  - service: ec2
    type: web_server
    specs:
      instance_type: t3.medium
    region: us-east-1
    quantity: 2
    usage_hours: 730  # 24/7 operation

  # Application Server Tier
  - service: ec2
    type: app_server
    specs:
      instance_type: t3.large
    region: us-east-1
    quantity: 2
    usage_hours: 730

  # Database Tier
  - service: rds
    type: primary_db
    specs:
      instance_type: db.t3.large
      engine: mysql
      storage_gb: 100
    region: us-east-1
    quantity: 1
    usage_hours: 730

  # Storage
  - service: s3
    type: app_storage
    specs:
      storage_class: Standard
      storage_gb: 500
    region: us-east-1

  # Backup Storage
  - service: s3
    type: backup_storage
    specs:
      storage_class: Standard-IA
      storage_gb: 1000
    region: us-east-1 